apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lyku
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lyku
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lyku
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lyku
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lyku
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlob-tenant/rhtap-demo-app/hacbs-test-project-lyku@sha256:51e3353cf2b28ca819925009c94c728d7f5061b4ef630e50629aa0824ddce126
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
