apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lyku
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlob-tenant/rhtap-demo-app/hacbs-test-project-lyku@sha256:51e3353cf2b28ca819925009c94c728d7f5061b4ef630e50629aa0824ddce126
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
